const tableFeilds = {
  realFields: [
    "Candidate Name",
    "Email ID",
    "Status",
    "Cv Submission Date",
    "Mobile Number",
    "Current CTC",
    "Expected CTC",
    "We offered",
    "Current CTC Breakups",
    "Expected CTC Breakups",
    "Offer Breakups",
    "Role",
    "Notice Period",
    "Current Location",
    "Preferred Location",
    "Vendor Name",
    "CBSI Position ID",
    "Position Shared date",
    "Total Job Changes",
    "Position Code",
    "Team",
    "Candidate Id",
    "Tower Lead",
    "Category",
    "Gender",
    "Qualification",
    "Current Company",
    "Offers in Hand",
    "Reason to Leave the Cur.Org",
    "Status",
    "Grade",
    "Total years of experience",
    "Current Company and working since",
    "Relevant years of experience",
    "Technologies worked on",
    "Skills",
    "Time Slot",
    "Date of Sharing",
    "Diversity",
    "Req ID",
    "Remarks",
    "Comments (if any)",
  ],
  cleanFields: [
    "CANDIDATE_NAME",
    "EMAIL_ID",
    "SelectedPhaseIndex",
    "CV_SUBMISSION_DATE",
    "CONTACT_NO",
    "C_CTC",
    "E_CTC",
    "WE_OFFERED",
    "C_CTC_BREAKUPS",
    "E_CTC_BREAKUPS",
    "OFFER_BREAKUPS",
    "CURRENT_DESIGNATION",
    "NOTICE_PERIOD",
    "CURRENT_LOCATION",
    "HIRING_LOCATION",
    "VENDOR_NAME",
    "CBSI_POSITION_ID",
    "POSITION_SHARED_DATE",
    "TOTAL_JOB_CHANGES",
    "POSITION_CODE",
    "TEAM",
    "CANDIDATE_ID",
    "TOWER_LEAD",
    "CATEGORY",
    "GENDER",
    "QUALIFICATION",
    "CURRENT_COMPANY",
    "COUNTER_OFFER",
    "REASON_FOR_CHANGE",
    "STATUS",
    "GRADE",
    "YEAR_OF_EXPERIENCE",
    "CURRENT_COMPANY_AND_WORKING_SINCE",
    "RELEVANT_YEARS_OF_EXPERIENCE",
    "TECHNOLOGIES_WORKED_ON",
    "SKILLS",
    "TIME_SLOT",
    "DATE_OF_SHARING",
    "DIVERSITY",
    "REQ_ID",
    "REMARKS",
    "COMMENTS",
  ],
  typeFeilds: [
    "string",
    "string",
    "string",
    "date",
    "phone",
    "number",
    "number",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "date",
    "number",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "string",
    "number",
    "string",
    "number",
    "string",
    "string",
    "string",
    "date",
    "string",
    "string",
    "string",
    "string",
  ],
};

const topicsData = {
  BASIC: {
    realFields: [
      "Current CTC Breakups",
      "Expected CTC Breakups",
      "We Offered",
      "Offer Breakups",
      "Total Job Changes",
      "Reason to Leave the Cur.Org",
      "Skills",
      "Technologies worked on",
      "Comments (if any)",
      "Database",
      "Candidate Name",
      "Email ID",
      "Cv Submission Date",
      "Mobile Number",
      "Current CTC",
      "Expected CTC",
      "Role",
      "Notice Period",
      "Current Location",
      "Preferred Location",
      "Vendor Name",
      "CBSI Position ID",
      "Position Shared date",
      "Position Code",
      "Team",
      "Candidate Id",
      "Tower Lead",
      "Category",
      "Gender",
      "Qualification",
      "Current Company",
      "Offers in Hand",
      "Status",
      "Grade",
      "Total years of experience",
      "Current Company and working since",
      "Relevant years of experience",
      "Time Slot",
      "Date of Sharing",
      "Diversity",
      "Req ID",
      "Remarks",
      "Org worked with",
      "Storage",
      "Experience in SAN",
      "Key systems experience",
      "People management experience",
      "Configuration",
      "Automation",
      "Cloud",
      "Monitoring tools",
      "Datacentre management",
      "Grade fitment",
      "Currently works with",
      "Career Gap",
      "Server",
      "Certification",
      "Windows and Vmware",
      "Scripting",
      "Windows",
      "Linux",
      "Ticketing tool",
      "Responsibility as app support engineer",
      "Year of Passing",
      "Managerial years of experience",
      "No. of People reporting",
      "Details of People reporting",
      "GAP in employment",
      "Current Fixed",
      "Variable Pay",
      "Benefits",
    ],
    cleanFields: [
      "C_CTC_BREAKUPS",
      "E_CTC_BREAKUPS",
      "WE_OFFERED",
      "OFFER_BREAKUPS",
      "TOTAL_JOB_CHANGES",
      "REASON_FOR_CHANGE",
      "SKILLS",
      "TECHNOLOGIES_WORKED_ON",
      "COMMENTS",
      "DATABASE",
      "CANDIDATE_NAME",
      "EMAIL_ID",
      "CV_SUBMISSION_DATE",
      "CONTACT_NO",
      "C_CTC",
      "E_CTC",
      "CURRENT_DESIGNATION",
      "NOTICE_PERIOD",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "VENDOR_NAME",
      "CBSI_POSITION_ID",
      "POSITION_SHARED_DATE",
      "POSITION_CODE",
      "TEAM",
      "CANDIDATE_ID",
      "TOWER_LEAD",
      "CATEGORY",
      "GENDER",
      "QUALIFICATION",
      "CURRENT_COMPANY",
      "COUNTER_OFFER",
      "STATUS",
      "GRADE",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY_AND_WORKING_SINCE",
      "RELEVANT_YEARS_OF_EXPERIENCE",
      "TIME_SLOT",
      "DATE_OF_SHARING",
      "DIVERSITY",
      "REQ_ID",
      "REMARKS",
      "ORG_WORKED_WITH",
      "STORAGE",
      "EXPERIENCE_IN_SAN",
      "KEY_SYSTEMS_EXPERIENCE",
      "PEOPLE_MANAGEMENT_EXPERIENCE",
      "CONFIGURATION",
      "AUTOMATION",
      "CLOUD",
      "MONITORING_TOOLS",
      "DATACENTRE_MANAGEMENT",
      "GRADE_FITMENT",
      "CURRENTLY_WORKS_WITH",
      "CAREER_GAP",
      "SERVER",
      "CERTIFICATION",
      "WINDOWS_AND_VMWARE",
      "SCRIPTING",
      "WINDOWS",
      "LINUX",
      "TICKETING_TOOL",
      "RESPONSIBILITY",
      "YEAR_OF_PASSING",
      "MANAGERIAL_YEARS_OF_EXPERIENCE",
      "NO_PEOPLE_REPORTING",
      "DETAIL_PEOPLE_REPORTING",
      "EMPLOYMENT_GAP",
      "CURRENT_FIXED",
      "VARIABLE_PAY",
      "BENEFITS",
    ],
    typeFeilds: [
      "string",
      "string",
      "string",
      "string",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "date",
      "phone",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "date",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "number",
      "string",
      "number",
      "string",
      "date",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "number",
      "string",
      "string",
      "number",
      "string",
      "string",
      "string",
    ],
  },

  PETRUS_TECHNOLOGIES: {
    realFields: [
      "Cv Submission Date",
      "Candidates",
      "Mobile Number",
      "Email ID",
      "Role",
      "Year of Experience",
      "Current Employer",
      "Current CTC",
      "Expected CTC",
      "Notice Period",
      "Counter Offer",
      "Current Location",
      "Preferred Location",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "CANDIDATE_NAME",
      "CONTACT_NO",
      "EMAIL_ID",
      "CURRENT_DESIGNATION",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "COUNTER_OFFER",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
    ],
    typeFeilds: [
      "date",
      "string",
      "phone",
      "string",
      "string",
      "number",
      "string",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
    ],
  },

  CHUBB_1_PRANOUTI_AND_ANAND: {
    realFields: [
      "Vendor Name",
      "CBSI Position ID",
      "Position Shared date",
      "Tower Lead",
      "Category",
      "CV Submission Date",
      "Candidate ID",
      "Candidate Name",
      "Gender",
      "Role",
      "Contact No.",
      "Email ID",
      "Qualification",
      "Total Exp",
      "Current Company",
      "Current Location",
      "Hiring Location",
      "Current CTC",
      "Expected CTC",
      "Offers in Hand",
      "Notice Period",
    ],
    cleanFields: [
      "VENDOR_NAME",
      "CBSI_POSITION_ID",
      "POSITION_SHARED_DATE",
      "TOWER_LEAD",
      "CATEGORY",
      "CV_SUBMISSION_DATE",
      "CANDIDATE_ID",
      "CANDIDATE_NAME",
      "GENDER",
      "CURRENT_DESIGNATION",
      "CONTACT_NO",
      "EMAIL_ID",
      "QUALIFICATION",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "C_CTC",
      "E_CTC",
      "COUNTER_OFFER",
      "NOTICE_PERIOD",
    ],
    typeFeilds: [
      "string",
      "string",
      "date",
      "string",
      "string",
      "date",
      "string",
      "string",
      "string",
      "string",
      "phone",
      "string",
      "string",
      "number",
      "string",
      "string",
      "string",
      "number",
      "number",
      "string",
      "string",
    ],
  },

  CHUBB_2_VINOTH_AND_KALYANI: {
    realFields: [
      "Tower Lead",
      "Cv Submission Date",
      "CBSI Position ID",
      "Candidate Name",
      "Role",
      "Contact No",
      "Email ID",
      "Gender",
      "Qualification",
      "Total Exp",
      "Current Company",
      "Current Location",
      "Hiring Location",
      "Current CTC",
      "Expected CTC",
      "Counter Offer",
      "Notice Period",
    ],
    cleanFields: [
      "TOWER_LEAD",
      "CV_SUBMISSION_DATE",
      "CBSI_POSITION_ID",
      "CANDIDATE_NAME",
      "CURRENT_DESIGNATION",
      "CONTACT_NO",
      "EMAIL_ID",
      "GENDER",
      "QUALIFICATION",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "C_CTC",
      "E_CTC",
      "COUNTER_OFFER",
      "NOTICE_PERIOD",
    ],
    typeFeilds: [
      "string",
      "date",
      "string",
      "string",
      "string",
      "phone",
      "string",
      "string",
      "string",
      "number",
      "string",
      "string",
      "string",
      "number",
      "number",
      "string",
      "string",
    ],
  },

  CHUBB_3_PRIYANCA_AND_NITHYA: {
    realFields: [
      "Cv Submission Date",
      "Sourced Date",
      "Position code",
      "Team",
      "Position",
      "Name",
      "Contact No",
      "Email ID",
      "Total Exp.",
      "Current Org",
      "Current CTC",
      "Exp.CTC",
      "Notice Period",
      "Current Location",
      "Preferred Location",
      "Offers in Hand",
      "Reason to Leave the Cur.Org",
      "Status",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "SOURCED_DATE",
      "POSITION_CODE",
      "TEAM",
      "CURRENT_DESIGNATION",
      "CANDIDATE_NAME",
      "CONTACT_NO",
      "EMAIL_ID",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "COUNTER_OFFER",
      "REASON_FOR_CHANGE",
      "STATUS",
    ],
    typeFeilds: [
      "date",
      "date",
      "string",
      "string",
      "string",
      "string",
      "phone",
      "string",
      "number",
      "string",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
    ],
  },

  TRANSUNION: {
    realFields: [
      "Cv Submission Date",
      "Grade",
      "Candidate Name",
      "Email ID",
      "Phone Number",
      "Total years of experience",
      "Current Company and working since",
      "Reason for Change",
      "Relevant years of experience",
      "Technologies worked on",
      "Current Location",
      "Preferred Location",
      "CTC",
      "E CTC",
      "Offers in Hand",
      "Notice Period",
      "Total Job Changes",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "GRADE",
      "CANDIDATE_NAME",
      "EMAIL_ID",
      "CONTACT_NO",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY_AND_WORKING_SINCE",
      "REASON_FOR_CHANGE",
      "RELEVANT_YEARS_OF_EXPERIENCE",
      "TECHNOLOGIES_WORKED_ON",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "C_CTC",
      "E_CTC",
      "COUNTER_OFFER",
      "NOTICE_PERIOD",
      "TOTAL_JOB_CHANGES",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "string",
      "phone",
      "number",
      "string",
      "string",
      "number",
      "string",
      "string",
      "string",
      "number",
      "number",
      "string",
      "string",
      "number",
    ],
  },

  CITCO: {
    realFields: [
      "Cv Submission Date",
      "Candidates",
      "Mobile Number",
      "Email Id",
      "Role",
      "Year of Experience",
      "Current Employer",
      "Current CTC",
      "Expected CTC",
      "Notice Period",
      "Counter Offer",
      "Current Location",
      "Preferred Location",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "CANDIDATE_NAME",
      "CONTACT_NO",
      "EMAIL_ID",
      "CURRENT_DESIGNATION",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "COUNTER_OFFER",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
    ],
    typeFeilds: [
      "date",
      "string",
      "phone",
      "string",
      "string",
      "number",
      "string",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
    ],
  },

  CRISIL: {
    realFields: [
      "Cv Submission Date",
      "Candidate Name",
      "Mobile No",
      "Email ID",
      "Current Organization",
      "Current Designation",
      "Qualification",
      "Over all Exp",
      "Current CTC",
      "Expected CTC",
      "Notice Period",
      "Counter Offer",
      "Current Location",
      "Hiring Location",
      "Reason for Change",
      "Skills",
      "Time Slot",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "CANDIDATE_NAME",
      "CONTACT_NO",
      "EMAIL_ID",
      "CURRENT_COMPANY",
      "CURRENT_DESIGNATION",
      "QUALIFICATION",
      "YEAR_OF_EXPERIENCE",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "COUNTER_OFFER",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "REASON_FOR_CHANGE",
      "SKILLS",
      "TIME_SLOT",
    ],
    typeFeilds: [
      "date",
      "string",
      "phone",
      "string",
      "string",
      "string",
      "string",
      "number",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
    ],
  },

  REGTECH: {
    realFields: [
      "Cv Submission Date",
      "Skill",
      "Candidate Name",
      "Mobile No",
      "Email ID",
      "Current Organization",
      "Current Designation",
      "Qualification",
      "Over all Exp",
      "Current CTC",
      "Expected CTC",
      "Notice Period",
      "Counter Offer",
      "Current Location",
      "Hiring Location",
      "Reason for Change",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "SKILLS",
      "CANDIDATE_NAME",
      "CONTACT_NO",
      "EMAIL_ID",
      "CURRENT_COMPANY",
      "CURRENT_DESIGNATION",
      "QUALIFICATION",
      "YEAR_OF_EXPERIENCE",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "COUNTER_OFFER",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "REASON_FOR_CHANGE",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "phone",
      "string",
      "string",
      "string",
      "string",
      "number",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
    ],
  },

  TRUSTRACE: {
    realFields: [
      "Cv Submission Date",
      "Skill",
      "Candidate Name",
      "Mobile No",
      "Email ID",
      "Current Organization",
      "Current Designation",
      "Qualification",
      "Over all Exp",
      "Current CTC",
      "Expected CTC",
      "Notice Period",
      "Counter Offer",
      "Hiring Location",
      "Status",
      "Reason for Change",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "SKILLS",
      "CANDIDATE_NAME",
      "CONTACT_NO",
      "EMAIL_ID",
      "CURRENT_COMPANY",
      "CURRENT_DESIGNATION",
      "QUALIFICATION",
      "YEAR_OF_EXPERIENCE",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "COUNTER_OFFER",
      "HIRING_LOCATION",
      "STATUS",
      "REASON_FOR_CHANGE",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "phone",
      "string",
      "string",
      "string",
      "string",
      "number",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
    ],
  },

  PURPLESLATE: {
    realFields: [
      "Cv Submission Date",
      "Skill",
      "Candidate Name",
      "Mobile No",
      "Email ID",
      "Current Organization",
      "Current Designation",
      "Qualification",
      "Over all Exp",
      "C CTC",
      "E CTC",
      "Notice Period",
      "Counter Offer",
      "Hiring Location",
      "Status",
      "Reason for Change",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "SKILLS",
      "CANDIDATE_NAME",
      "CONTACT_NO",
      "EMAIL_ID",
      "CURRENT_COMPANY",
      "CURRENT_DESIGNATION",
      "QUALIFICATION",
      "YEAR_OF_EXPERIENCE",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "COUNTER_OFFER",
      "HIRING_LOCATION",
      "STATUS",
      "REASON_FOR_CHANGE",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "phone",
      "string",
      "string",
      "string",
      "string",
      "number",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
    ],
  },

  AMERICAN_EXPRESS: {
    realFields: [
      "Cv Submission Date",
      "Date of Sharing",
      "Candidate Name",
      "Current Company",
      "Experience",
      "CCTC",
      "EXCTC",
      "Notice Period",
      "Email",
      "Contact No",
      "Skill Set",
      "Diversity",
      "Current Location",
      "Req ID",
      "Status",
      "Comments (if any)",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "DATE_OF_SHARING",
      "CANDIDATE_NAME",
      "CURRENT_COMPANY",
      "YEAR_OF_EXPERIENCE",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "EMAIL_ID",
      "CONTACT_NO",
      "SKILLS",
      "DIVERSITY",
      "CURRENT_LOCATION",
      "REQ_ID",
      "STATUS",
      "COMMENTS",
    ],
    typeFeilds: [
      "date",
      "date",
      "string",
      "string",
      "number",
      "number",
      "number",
      "string",
      "string",
      "phone",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
    ],
  },

  DINAKARAN: {
    realFields: [
      "Cv Submission Date",
      "Grade",
      "Candidate Name",
      "Email ID",
      "Phone Number",
      "Total years of experience",
      "Current Company and working since",
      "Reason for Change",
      "Relevant years of experience",
      "Technologies worked on",
      "Current Location",
      "Preferred Location",
      "CTC",
      "E CTC",
      "Notice Period",
      "Total Job Changes",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "GRADE",
      "CANDIDATE_NAME",
      "EMAIL_ID",
      "CONTACT_NO",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY_AND_WORKING_SINCE",
      "REASON_FOR_CHANGE",
      "RELEVANT_YEARS_OF_EXPERIENCE",
      "TECHNOLOGIES_WORKED_ON",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "TOTAL_JOB_CHANGES",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "string",
      "phone",
      "number",
      "string",
      "string",
      "number",
      "string",
      "string",
      "string",
      "number",
      "number",
      "string",
      "string",
    ],
  },

  BHAKTHI: {
    realFields: [
      "Cv Submission Date",
      "Grade",
      "Candidate Name",
      "Email ID",
      "Phone Number",
      "Total years of experience",
      "Current Company and working since",
      "Relevant years of experience",
      "Technologies worked on",
      "Current Location",
      "Preferred Location",
      "CTC",
      "Offer (if any)",
      "E CTC",
      "Notice Period",
      "Reason for Change",
      "Org worked with",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "GRADE",
      "CANDIDATE_NAME",
      "EMAIL_ID",
      "CONTACT_NO",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY_AND_WORKING_SINCE",
      "RELEVANT_YEARS_OF_EXPERIENCE",
      "TECHNOLOGIES_WORKED_ON",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "C_CTC",
      "COUNTER_OFFER",
      "E_CTC",
      "NOTICE_PERIOD",
      "REASON_FOR_CHANGE",
      "ORG_WORKED_WITH",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "string",
      "phone",
      "number",
      "string",
      "number",
      "string",
      "string",
      "string",
      "number",
      "string",
      "number",
      "string",
      "string",
      "string",
    ],
  },

  DHEERAJ: {
    realFields: [
      "Cv Submission Date",
      "Shared Date",
      "Candidates",
      "Mobile Number",
      "Email Id",
      "Role",
      "Current Location",
      "Preferred Location",
      "Year of Experience",
      "Current Employer",
      "Current CTC",
      "Expected CTC",
      "Notice Period",
      "Counter Offer",
      "Remarks",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "POSITION_SHARED_DATE",
      "CANDIDATE_NAME",
      "CONTACT_NO",
      "EMAIL_ID",
      "CURRENT_DESIGNATION",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_COMPANY",
      "C_CTC",
      "E_CTC",
      "NOTICE_PERIOD",
      "COUNTER_OFFER",
      "REMARKS",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "phone",
      "string",
      "string",
      "string",
      "string",
      "number",
      "string",
      "number",
      "number",
      "string",
      "string",
      "string",
    ],
  },

  RADHIKA_1: {
    realFields: [
      "Cv Submission Date",
      "Name",
      "Mail",
      "Mobile",
      "Total experience (in Years)",
      "Grade fitment",
      "Currently works with",
      "Career Gap",
      "Server",
      "Certification",
      "Windows and Vmware",
      "Reason for change",
      "Storage",
      "Experience in SAN",
      "Key systems experience",
      "People management experience",
      "Configuration",
      "Automation",
      "Cloud",
      "Monitoring tools",
      "Datacentre management",
      "Current location",
      "Notice period",
      "Offer in hand",
      "Current CTC",
      "Expected CTC",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "CANDIDATE_NAME",
      "EMAIL_ID",
      "CONTACT_NO",
      "YEAR_OF_EXPERIENCE",
      "GRADE_FITMENT",
      "CURRENTLY_WORKS_WITH",
      "CAREER_GAP",
      "SERVER",
      "CERTIFICATION",
      "WINDOWS_AND_VMWARE",
      "REASON_FOR_CHANGE",
      "STORAGE",
      "EXPERIENCE_IN_SAN",
      "KEY_SYSTEMS_EXPERIENCE",
      "PEOPLE_MANAGEMENT_EXPERIENCE",
      "CONFIGURATION",
      "AUTOMATION",
      "CLOUD",
      "MONITORING_TOOLS",
      "DATACENTRE_MANAGEMENT",
      "CURRENT_LOCATION",
      "NOTICE_PERIOD",
      "COUNTER_OFFER",
      "C_CTC",
      "E_CTC",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "phone",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "number",
      "number",
    ],
  },

  RADHIKA_2: {
    realFields: [
      "Cv Submission Date",
      "Name",
      "Mail",
      "Mobile",
      "Total experience",
      "Current Location",
      "Currently works with",
      "Career Gap",
      "Windows",
      "Linux",
      "Ticketing tool",
      "Monitoring tool",
      "Scripting",
      "Notice period to join",
      "Responsibility as app support engineer",
      "Current CTC",
      "Expected CTC",
      "Counter Offer",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "CANDIDATE_NAME",
      "EMAIL_ID",
      "CONTACT_NO",
      "YEAR_OF_EXPERIENCE",
      "CURRENT_LOCATION",
      "CURRENTLY_WORKS_WITH",
      "CAREER_GAP",
      "WINDOWS",
      "LINUX",
      "TICKETING_TOOL",
      "MONITORING_TOOLS",
      "SCRIPTING",
      "NOTICE_PERIOD",
      "RESPONSIBILITY",
      "C_CTC",
      "E_CTC",
      "COUNTER_OFFER",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "phone",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "number",
      "number",
      "string",
    ],
  },

  NAVITHA: {
    realFields: [
      "Cv Submission Date",
      "Role",
      "Grade",
      "Candidate Name",
      "Email ID",
      "Phone Number",
      "Current Company and working since",
      "Reason for Change",
      "Education",
      "Year of Passing",
      "Gap In Education",
      "Total years of experience",
      "Relevant years of experience",
      "Managerial years of experience",
      "No. of People reporting",
      "Details of People reporting",
      "Technologies worked on",
      "Current Location",
      "Preferred Location",
      "Notice Period",
      "Total Job Changes",
      "GAP in employment",
      "Current CTC",
      "Current Fixed",
      "Variable Pay",
      "Benefits",
      "Counter offer details (If any )",
      "Expected CTC (Fixed)",
    ],
    cleanFields: [
      "CV_SUBMISSION_DATE",
      "CURRENT_DESIGNATION",
      "GRADE",
      "CANDIDATE_NAME",
      "EMAIL_ID",
      "CONTACT_NO",
      "CURRENT_COMPANY_AND_WORKING_SINCE",
      "REASON_FOR_CHANGE",
      "QUALIFICATION",
      "YEAR_OF_PASSING",
      "CAREER_GAP",
      "YEAR_OF_EXPERIENCE",
      "RELEVANT_YEARS_OF_EXPERIENCE",
      "MANAGERIAL_YEARS_OF_EXPERIENCE",
      "NO_PEOPLE_REPORTING",
      "DETAIL_PEOPLE_REPORTING",
      "TECHNOLOGIES_WORKED_ON",
      "CURRENT_LOCATION",
      "HIRING_LOCATION",
      "NOTICE_PERIOD",
      "TOTAL_JOB_CHANGES",
      "EMPLOYMENT_GAP",
      "C_CTC",
      "CURRENT_FIXED",
      "VARIABLE_PAY",
      "BENEFITS",
      "COUNTER_OFFER",
      "E_CTC",
    ],
    typeFeilds: [
      "date",
      "string",
      "string",
      "string",
      "string",
      "phone",
      "string",
      "string",
      "string",
      "string",
      "string",
      "number",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "string",
      "number",
      "number",
      "string",
      "string",
      "string",
      "string",
      "number",
    ],
  },
};

const topicsRealNames = [
  "Basic Information",
  "Petrus Technologies",
  "CHUBB 1 (Pranouti & Anand)",
  "CHUBB 2 (Vinoth & Kalyani)",
  "CHUBB 3 (Priyanca & Nithya)",
  "Transunion",
  "Citco",
  "Crisil",
  "Regtech",
  "Trustrace",
  "Purpleslate",
  "American Express",
  "Dinakaran",
  "Bhakthi",
  "Dheeraj",
  "Radhika Infrastructure",
  "Radhika Application Support",
  "Navitha",
];

const topicsCleanNames = [
  "BASIC",
  "PETRUS_TECHNOLOGIES",
  "CHUBB_1_PRANOUTI_AND_ANAND",
  "CHUBB_2_VINOTH_AND_KALYANI",
  "CHUBB_3_PRIYANCA_AND_NITHYA",
  "TRANSUNION",
  "CITCO",
  "CRISIL",
  "REGTECH",
  "TRUSTRACE",
  "PURPLESLATE",
  "AMERICAN_EXPRESS",
  "DINAKARAN",
  "BHAKTHI",
  "DHEERAJ",
  "RADHIKA_1",
  "RADHIKA_2",
  "NAVITHA",
];
